name: CI

on: push

env:
  MIX_ENV: test
  MIX_ARCHIVES: deps

jobs:
  format:
    name: "Check Formatted"

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
      - uses: actions/checkout@v1
      - name: Check formatted
        run: mix format --check-formatted

  deps:
    name: Dependencies

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-v2-
      - name: Install dependencies
        run: |
          mix local.rebar --force --if-missing
          mix local.hex --force --if-missing
          mix deps.get

  compile:
    name: Compile

    needs: deps

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Compile
        run: mix compile --warnings-as-errors

  test:
    name: Tests

    needs: [deps, compile]

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Run tests
        run: mix coveralls.json
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  credo:
    name: Credo

    needs: [deps, compile]

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Run credo
        run: mix credo --strict

  dialyzer:
    name: Dialyzer

    needs: [deps, compile]

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Run dialyzer
        run: mix dialyzer --halt-exit-status
